### ISSUE TITLE
crash on load

### ISSUE THREAD

**Issue by defautluser0** [Fusion-Flux/Thinking-With-Portatos#118]
newest (alpha) 1.19.2 from modrinth
[crash-2023-05-14_16.04.55.4638-quilt_loader.txt](https://github.com/Fusion-Flux/Portal-Cubed/files/11472131/crash-2023-05-14_16.04.55.4638-quilt_loader.txt)
[latest.log](https://github.com/Fusion-Flux/Portal-Cubed/files/11472132/latest.log)

**Comment by defautluser0** [comment]
and yes, im on quilt and i have tried non alpha

**Comment by Cart3r1234** [comment]
Seems to be a gravity API issue, and not something specific to portal cubed.  Try an updated version of portal cubed and/or gravity, as it may have been fixed already.  If not, report to Gravity API's issues page instead.
