### ISSUE TITLE
on 1.18.2 portal gun is very buggy in multiplayer

### ISSUE THREAD

**Issue by Agent-Maxwell** [Fusion-Flux/Thinking-With-Portatos#125]
I have not tested this in other versions, but on a 1.18.2 multiplayer server portals will teleport other nearby players seemingly at random. At one point it teleported four people inside the same wall, fix was to relog. I also see that 1.18.2 is a beta version so I understand if it is no longer supported.

**Comment by Fusion-Flux** [comment]
yeah 1.18.2 is no longer supported and newer versions are reciving large rewrites
