### ISSUE TITLE
[Cube Physics] Cubes cannot pass through portals

### ISSUE THREAD

**Issue by Cart3r1234** [Fusion-Flux/Thinking-With-Portatos#14]
Cubes treat portals (mostly) as the solid surface they are placed on, however their model seems to partially show through on the other side
![image](https://user-images.githubusercontent.com/69820300/115161825-bf855d80-a06d-11eb-9e6f-5a11d0932eab.png)

**Comment by TheAwesome98-Real** [comment]
I think the cubes collide with themselves.

**Comment by Ch1216** [comment]
They can now in the rewrite

**Comment by Fusion-Flux** [comment]
fixed

**Comment by Ch1216** [comment]
and now they can not

**Comment by Fusion-Flux** [comment]
ohp

**Comment by Fusion-Flux** [comment]
let me test

**Comment by Ch1216** [comment]
No, its not they cant pass though. more of they go though like the author  probs wanted the cubes to go though the portal and not no-clip it

**Comment by Fusion-Flux** [comment]
?

**Comment by Ch1216** [comment]
https://user-images.githubusercontent.com/68875386/169630190-7f3d57e9-9d7d-4395-a21f-29b3f0f5e1b8.mp4

Yes the cube passes through the portal, but not in the way you expect (it teleporting through the portal)

So yes cubes can pass though portals, but not in the way you expect

**Comment by Fusion-Flux** [comment]
ah yeah i cant really do that
