### ISSUE TITLE
[Cubes] Cubes don't activate pressure plates unless the plate is already pressed

### ISSUE THREAD

**Issue by Cart3r1234** [Fusion-Flux/Thinking-With-Portatos#16]
Cubes do not activate pressure plates unless they have already been pressed down, in which case the cube will hold it, but moving the cube off and back onto the plate causes the plate to not be pressed again. 
![image](https://user-images.githubusercontent.com/69820300/115162236-67038f80-a070-11eb-9b55-b4666790bfe8.png)

**Comment by Ch1216** [comment]
Fixed in the rewrite
