### ISSUE TITLE
[Excursion Funnel] Items caught in excursion funnels will travel for a short distance, but then get teleported to the base of the funnel

### ISSUE THREAD

**Issue by Cart3r1234** [Fusion-Flux/Thinking-With-Portatos#17]
Throwing an item into an excursion funnel will cause it to travel along the path as expected for a few seconds, but then suddenly teleport to the base of the funnel and sometimes to the ground below the base.  This happens repeatedly for upwards facing funnels, while with sideways and downwards funnels the item will teleport to the start of the funnel and just fall out of it/get stuck on the ground

**Comment by Ch1216** [comment]
Fixed in the rewrite
