### ISSUE TITLE
[Feature Suggestion] In Adventure Mode, the player should only be able to place portals on white panel surfaces

### ISSUE THREAD

**Issue by Cart3r1234** [Fusion-Flux/Thinking-With-Portatos#23]
In adventure mode, the player should only be able to place portals on surfaces made up of the white wall/floor panels, increasing adventure map potential.

**Comment by WilliamPiette** [comment]
one could go further and make portal-able surfaces configurable, to provide as many block options as needed for map creation or any other use really

**Comment by Cart3r1234** [comment]
Added in a recent commit; surfaces that portals can be placed on in adventure mode is now a tag.
