### ISSUE TITLE
add more things

### ISSUE THREAD

**Issue by Kierancraft** [Fusion-Flux/Thinking-With-Portatos#31]
Add the singular portal guns for only orange and only blue portals, add the portal emitters (the things that make portals with power), add the portal gun stands for the single portal guns, add the cameras, and add the floor buttons

**Comment by Kierancraft** [comment]
also adding the wall and floor power would be cool

**Comment by Cart3r1234** [comment]
The mod is still a work in progress, so many things are missing or will be added in the future.  Single-portal guns, floor buttons, and Autoportals have been added in dev versions.
