### ISSUE TITLE
Portals dont translate well going horizontal to vertical in certain situations

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#35]
If portal 1 is touching the floor on a wall and portal 2 in on the ground if you go though portal 2 you will get stuck

**Comment by Ch1216** [comment]
Seems to be fixed in the latest modrinth version

**Comment by Fusion-Flux** [comment]
Fixed

**Comment by Ch1216** [comment]
Not fixed if your in multiplayer and your not the host
