### ISSUE TITLE
A sliding door drops 2 sliding doors

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#37]
How to reproduce
1. Place sliding door
2. Break it in any way (mine it, explode it)
3. See it drops 2 even though its 1 door

If I has to guess why it happen because its 2 blocks but that doesn't happens to doors (maybe there a door fix you have to apply?)
Maybe its due to tags? (there a #minecraft:doors tag)

#27 (presumably) would have fixed this by having only one half of the door drop a item

**Comment by Fusion-Flux** [comment]
fixed
