### ISSUE TITLE
Missing subtitle

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#38]
subtitles.portalcubed.portal_invalid_surface (only happens when shooting a portal to the sky/out of range) (Doesn't really make sense considering its name)
Is missing
Suggestions:
"Portal can't place"/"Portal can't open"/"Portal failed to place"

**Comment by Cart3r1234** [comment]
This has been fixed in dev versions.  The subtitle now properly displays for all scenarios, and was changed to "Portal Gun Failed".  
To download a version of the latest build, use this link: https://nightly.link/Fusion-Flux/Portal-Cubed/workflows/build/1.19.2/Artifact.zip
