### ISSUE TITLE
Putting a cube in front of a portal causes going through the portal to be glitchy

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#41]
If there is a cube in front of a portal (easier to place a cube then a portal behind it (its glitchy (#42) when you try to put a cube though a portal)) and you go through glitches will ensue

This didnt happen in old version because the hitbox went though the portal (with the rendering/Immersive portals) and you used to be able to move the portal with your hitbox

**Comment by Fusion-Flux** [comment]
fixed

**Comment by Ch1216** [comment]
You still can get stuck if you got slowly though a portal

**Comment by Fusion-Flux** [comment]
yeah havent fully figured out a reason why this happens or how to fix it yet

**Comment by Ch1216** [comment]
seems fully fixed in 2.1.7

**Comment by Fusion-Flux** [comment]
had no clue i fixed it

**Comment by Ch1216** [comment]
> had no clue i fixed it

yeah now when you got though a portal you have no collision with the cube until you get out of its hitbox, better than getting stuck forever
