### ISSUE TITLE
Putting a cube though a portal with a portal gun teleports said cube from your location and the other end of the portal

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#42]
If you grab a cube then put it though a portal it'll go through the portal then zoom back where it should be if there were no portal

https://user-images.githubusercontent.com/68875386/169545540-336215c3-2575-4b40-af78-ac10269279b1.mp4

It might happen because it has no collision with blocks maybe rendering would fix this/make it easier to visualize somehow?

**Comment by Fusion-Flux** [comment]
fixed
