### ISSUE TITLE
You can interact with cubes while grabbing them

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#45]
In portal games you can't interact with cubes while grabbing them
It also means you can jump on a cube and gain height by jumping, you can also walk on them (only if you are sneaking)

**Comment by Fusion-Flux** [comment]
reworked cubes so this doesnt happen they still can slightly push the player but i cant really fix that
also i added some code so its now possible to throw the cube!
