### ISSUE TITLE
Some entities interact weirdly with funnels

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#46]
https://user-images.githubusercontent.com/68875386/169617501-79f159fc-b7ee-45fc-9e0e-1669d05016f6.mp4

**Comment by Fusion-Flux** [comment]
ah yeah im fully aware of this problem
its still completely unknown what is causing it unfortunately

**Comment by Fusion-Flux** [comment]
should note this isnt only a issue with cubes
its an issue with all entities

**Comment by Ch1216** [comment]
Doesnt seem to happen to boats for some reason

**Comment by Fusion-Flux** [comment]
huh
strange

**Comment by Cart3r1234** [comment]
This has been fixed in dev versions.  
To download a version of the latest build, use this link: https://nightly.link/Fusion-Flux/Portal-Cubed/workflows/build/1.19.2/Artifact.zip
