### ISSUE TITLE
Can't use portals in multiplayer if distance between portal is greater than 10

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#47]
If two portals are 11 or more blocks apart you will get stuck on them as according to the server you "moved too quickly" teleporting back to where you where, (the portal) which then teleports you to the other portal making you "move too quickly" teleporting you back, making an unescapable loop

The host isn't affected by this in LAN worlds

**Comment by Fusion-Flux** [comment]
yeah makes sense
a fix for this is making the teleportation logic clientsided 
problem is i dont know how to do that

**Comment by Ch1216** [comment]
fixed in 2.1.7
