### ISSUE TITLE
Adhesion gel doesn't let go when portal exist in certain areas of the world

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#48]
[Video, Because bug is weird its requires a video I cant upload to Github](https://www.youtube.com/watch?v=XTks4eYvisA)
How? What? Why? No Idea
Only happens when that specific is structure is built and the portals are around the same are and exact same X coordinate

**Comment by Ch1216** [comment]
Seems fixed in 2.1.7
although 2 times I jumped multiple times and it didnt unstick me when I was upside down, but I cant replicate it

**Comment by Ch1216** [comment]
Ok, its still weird but not as weird, updated video+ description

**Comment by Cart3r1234** [comment]
This has been fixed in dev versions, as adhesion gel was rewritten.  
To download a version of the latest build, use this link: https://nightly.link/Fusion-Flux/Portal-Cubed/workflows/build/1.19.2/Artifact.zip
