### ISSUE TITLE
Cubes stay in your gravity when held

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#50]
If you are grabbing a cube on an unregular gravity it will fall into whatever gravity for a second until it goes regular down on its own (ex: your gravity is up, you drop the cube, the cube is gonna fall up for 2 second before resetting its gravity to down on its own (somehow))

This can be a nuances if your upside down with adhesion gel and trying to make a cube fall down, but it falls up and sticks into the adhesion gel

**Comment by Fusion-Flux** [comment]
will be fixed in the next version
