### ISSUE TITLE
Wall Adhesion gel sticking breaks if you stick by only the head

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#53]
https://youtu.be/ABkdjacmbS0

I don't know if its possible but it may be fixed if only the bottom part of the player hitbox could interact with adhesion gel (maybe .1 units upwards from the bottom would have to do it(maybe the entire legs part)

**Comment by Cart3r1234** [comment]
This has been fixed in dev versions, as adhesion gel was rewritten.  
To download a version of the latest build, see this link: https://nightly.link/Fusion-Flux/Portal-Cubed/workflows/build/1.19.2/Artifact.zip
