### ISSUE TITLE
Placing a cube on top of a block where a portal is passes the cube though the portal

### ISSUE THREAD

**Issue by Ch1216** [Fusion-Flux/Thinking-With-Portatos#55]
https://user-images.githubusercontent.com/68875386/170624467-0f704144-7418-43b2-b7d1-0dc08628fa0f.mp4

Would have made video shorter but a trimmed video (Video shorter than the above one) is more than 10MB (|Github's size limit), how a shorter video is bigger than the original idk, maybe it gets data implanted when trimmed which makes no sense

**Comment by Fusion-Flux** [comment]
happens on all entities

**Comment by Ch1216** [comment]
how do you test that, I use spawn eggs, boats and mine and they don't get immediately teleported
