### ISSUE TITLE
Russian translation is invalid json

### ISSUE THREAD

**Issue by TheEpicBlock** [Fusion-Flux/Thinking-With-Portatos#58]
The Russian translation is missing a closing `"` on line 69

**Comment by TheEpicBlock** [comment]
Oh, I just saw #24 is actual open for this

**Comment by ImSpaceLover** [comment]
It was completely redone and this issue shouldn't occur in the latest version

**Comment by TheEpicBlock** [comment]
I checked all the branches, it appears to still be invalid on all of them

**Comment by ImSpaceLover** [comment]
It wasn't uploaded to GitHub yet
