### ISSUE TITLE
Not able to launch MC 1.18.2

### ISSUE THREAD

**Issue by Gamerbolts** [Fusion-Flux/Thinking-With-Portatos#61]
Hello I am using the latest beta and trying to get this mod onto my rather large modpack. It loaded and then crashed to desktop without a crash report. Here is my [latest.log](https://github.com/Fusion-Flux/Thinking-With-Portatos/files/8857428/latest.log) if that helps. It looks like a conflict with XP Bottles but I am not sure. Any help is appreciated thank you :)

**Comment by Fusion-Flux** [comment]
hmm you could try updating to the latest fabric version
2.2.1 though i have discontinued working on this mod for fabric as ive moved over to quilt

**Comment by Fusion-Flux** [comment]
oh right i dont touch CF for beta versions
https://modrinth.com/mod/portal-cubed/versions

**Comment by Gamerbolts** [comment]
Oh dang. I am making my modpack through curse :( thanks anyway. They don't allow non curse mods to go through.

**Comment by Fusion-Flux** [comment]
i could recommend using something like MultiMC or ATLauncher they are much nicer to use then CF and AtLauncher accepts adding mods from CF and Modrinth
