### ISSUE TITLE
Couldn't load tag gravitychanger:forbidden_entities as it is missing following references: create:contraption (from GravityChanger), create:stationary_contraption (from GravityChanger), create:gantry_contraption (from GravityChanger), create:super_glue (from GravityChanger), create:crafting_blueprint (from GravityChanger), create:seat (from GravityChanger)

### ISSUE THREAD

**Issue by Lolothepro** [Fusion-Flux/Thinking-With-Portatos#62]
When you load a world, this is in the logs: (1.18.2)
`Couldn't load tag gravitychanger:forbidden_entities as it is missing following references: create:contraption (from GravityChanger), create:stationary_contraption (from GravityChanger), create:gantry_contraption (from GravityChanger), create:super_glue (from GravityChanger), create:crafting_blueprint (from GravityChanger), create:seat (from GravityChanger)`

**Comment by Ch1216** [comment]
I think this only happens on the curseforge versions, modrinth has more versions
