### ISSUE TITLE
1.19.2 will not launch with mod installed

### ISSUE THREAD

**Issue by sgben521** [Fusion-Flux/Thinking-With-Portatos#64]
I have tried with no other mods besides QSL and with Rayon and Cloth Config but I get an error about GravityAPI every time

Log: https://paste.ee/p/Yz1iw

Edit: I have tried 2.2.6 - 2.2.8 to no avail

**Comment by MIPOHBOPOHIH** [comment]
i try download gravity api, rayon and cloth config for portal cubed, but it still didn't help

**Comment by Fusion-Flux** [comment]
the mod no longer uses rayon or cloth config
version 2.2.6 doesnt work so you likely need 2.2.8 so ill need a crash log from 2.2.8

**Comment by MIPOHBOPOHIH** [comment]
> мод больше не использует вискоза или ткань. Конфигурация версии 2.2.6 не работает, поэтому вам, вероятно, понадобится 2.2.8, поэтому мне нужен журнал сбоев из 2.2.8.

https://mclo.gs/E2kx5KA

**Comment by MIPOHBOPOHIH** [comment]
> the mod no longer uses rayon or cloth config version 2.2.6 doesnt work so you likely need 2.2.8 so ill need a crash log from 2.2.8

https://mclo.gs/E2kx5KA

**Comment by sgben521** [comment]
Here is a updated log, seems to be the same error

https://paste.ee/p/Ghkkz

also just Portal Cubed and QSL/QFAPI

**Comment by MIPOHBOPOHIH** [comment]
> Here is a updated log, seems to be the same error
> 
> https://paste.ee/p/Ghkkz
> 
> also just Portal Cubed and QSL/QFAPI

try to download https://modrinth.com/mod/gravity-api/version/0.7.20%2Bquilt

**Comment by Cart3r1234** [comment]
1.19.2 launch issues should be fixed in both the latest release and in dev builds.  The links to your logs have expired, so if the issue still occurs on newer versions, please attach a new log so we can investigate further.  To grab the latest dev build, use this link:  https://nightly.link/Fusion-Flux/Portal-Cubed/workflows/build/1.19.2/Artifact.zip
