### ISSUE TITLE
Pedestal buttons on forever

### ISSUE THREAD

**Issue by Problemreported** [Fusion-Flux/Thinking-With-Portatos#69]
I put a pedestal button and turned it on. I want to set it to a limited time when pressed. also I don't see any floor buttons in the mod's 
creative inventory tab. 

pls fix.

**Comment by Cart3r1234** [comment]
Floor buttons and other related testing elements are included in newer versions of the mod, however pedestal buttons with custom pulse lengths are not, and not currently planned as far as I know.

**Comment by Problemreported** [comment]
> Floor buttons and other related testing elements are included in newer versions of the mod, however pedestal buttons with custom pulse lengths are not, and not currently planned as far as I know.

Thanks
