### ISSUE TITLE
Funnel based crash

### ISSUE THREAD

**Issue by Problemreported** [Fusion-Flux/Thinking-With-Portatos#70]
Hey! I was trying to pack a funnel in the open however I accidentally placed it pointing to the sky in the open. it crashed and my sister got disconnected. I was running it on a LAN server. [here's the log from start to crash](https://paste.ee/p/dvCct). (Uploaded from multiMC). 

I suggest adding a limit for the funnel like the build height limit. or if there is a block place above it but isnt too far it will ignore the build height limit.

**Comment by Cart3r1234** [comment]
This issue has been fixed in a newer version of the mod.  Make sure you are using the most recent before submitting bug reports.  Funnels, Lasers, Bridges, and other test elements that extend are limited by default to 128, but can be configured in the mod settings.
