### ISSUE TITLE
Won't launch as part of Quilt modpack with mostly Fabric mods

### ISSUE THREAD

**Issue by SuperKnux** [Fusion-Flux/Thinking-With-Portatos#77]
1.19.2, Quilt Loader 0.17.7.
I've already tried it with and without Gravity API, and I found that the mod itself was the cause of the crashing, after I found that removing it allows the modpack to launch. I'm thinking that it has an incompatibility with one of the pure Fabric mods...
[latest.log](https://github.com/Fusion-Flux/Portal-Cubed/files/10171990/latest.log)

**Comment by Gaming32** [comment]
Gravity API is included in Portal Cubed. However, this issue appears to be fixed. Please download [the latest build of Portal Cubed](https://nightly.link/Fusion-Flux/Portal-Cubed/workflows/build/1.19.2/Artifact.zip) and try again.
